<resources>
    <string name="app_name">Git Users</string>
    <string name="error_generic">Unexpected error</string>

    <string name="common_close">"Close"</string>
    <string name="common_ok">"OK"</string>
    <string name="common_retry">"Retry"</string>

    <string name="popup_error_unknown_title">"Sorry, something went wrong!"</string>
    <string name="popup_error_unknown_body">"There was a problem processing your request. Please try again."</string>
    <string name="popup_error_timeout_title">"Oops...Our server overloaded!"</string>
    <string name="popup_error_timeout_body">"Apologies for the inconvenience! Weâ€™ll be back soon. Please try again later."</string>

    <string name="popup_error_no_connection_title">"You are currently offline!"</string>
    <string name="popup_error_no_connection_body">"Looks like your connection is interrupted. Check network connection and try again."</string>
</resources>